{
    'name': 'IATF',
    'version': '16.0.1.0',
    'category': 'Custom',
    'summary': '',
    'description': """""",
    'author': 'ASD',
    'price': 0,
    'license': 'LGPL-3',
    'sequence': 1,
    'currency': "INR",
    'website': 'https://asdsoftwares.com/',
    'depends': ['hr', 'base', 'sale', 'mrp', 'product', 'maintenance', 'crm', 'project', 'l10n_in','mail','global_translation'],
    'data': [
        'data/mail_template.xml',
        'data/approved_mail_template.xml',
        'views/menu_items.xml',
        'data/data.xml',
        # 'data/qr_document_types.xml',

        # 'data/equipment_sheet.xml',
        'security/ir.model.access.csv',

        # 'report/qr_manual_report.xml',  # Load the report template
        # 'views/mom_views.xml',
        # 'views/cft_team_views.xml',
        # 'views/formats.xml',
        # 'views/procedure.xml',
        'views/iatf_sign_off_members.xml',
        'views/risk_assessment.xml',
        'views/poko_yoko.xml',
        'views/team_feasibility_report.xml',
        'views/packaging_standard.xml',
        # 'views/part_development_process_views.xml',
        'views/customer_part_creation_views.xml',
        'views/quary_list_views.xml',
        'views/things_views.xml',
        'views/process_flow_views.xml',
        'views/apq_views.xml',
        'views/customer_specification_view.xml',
        'views/change_request.xml',
        'views/tracking_record.xml',
        # 'views/drawing_document.xml',
        'views/ppap_checklist.xml',
        'views/development_evaluation_cycle.xml',
        'views/key_character_history.xml',
        'views/customer_specification_requirement_view.xml',
        # 'views/symbole_conversion_tabel.xml',
        'views/npd_revire.xml',
        'views/special_characterhistory_specification.xml',
        # 'views/material_handling_request.xml',
        # 'views/responsible_matrix.xml',
        # 'views/control_method.xml',
        # 'views/review_of_operation.xml',
        # 'views/daily_quality_focuse.xml',
        # 'views/calling.xml',
        # 'views/iatf_teams.xml',
        'views/pfmea.xml',
        'views/control_plan.xml',
        'views/control_plan_assy.xml',
        'views/process_presentation.xml',
        'views/equipment_trackingsheet.xml',
        'views/tool_trackingsheet.xml',
        'views/gauge_tracking_sheet.xml',
        # 'views/image_reader.xml',
        # 'views/qr_code.xml',
        # 'views/qr_views.xml',
        'views/pfmea_two_view.xml',
        'views/pfmea_two_suggestion.xml',
        'views/risk_analysis.xml',
        'views/pfmea_dashboard.xml',
        'views/pfmea_dashboard_details.xml',
        'views/process_matrix_suggestions.xml',
        'views/manpower.xml',






    ],
    'external_dependencies': {
        'python': ['qrcode'],
        # 'bin': ['wkhtmltopdf'],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
