{
    'name': 'OHSAS-EHS',
    'version': '16.0.1.0',
    'category': 'Custom',
    'summary': '',
    'description': """""",
    'author': 'ASD',
    'price': 0,
    'license': 'LGPL-3',
    'sequence': 1,
    'currency': "INR",
    'website': 'https://asdsoftwares.com/',
    'depends': ['hr', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_items.xml',
        'views/ocp_final.xml',
        'views/legal_register_compliance.xml',
        'views/list_employees_health_checkup.xml',
        'views/ppe_matrix.xml',
        'views/safety_commitee_mom.xml',
        'views/statutory_compliance_status.xml',
        'views/hr_emp.xml',
        'views/near_miss_incident_record.xml',
        'views/menu_items.xml',
        'views/ehs_compliance_monitoring_check_sheet.xml',
        'views/legal_register.xml',
        'views/vehicle_inspection_views.xml',
        'views/observation_views.xml',
        'views/fire_extinguisher_views.xml',
        'views/emergency_response_team_views.xml',
        'views/ohs_incident_investigation_views.xml',
        'views/check_point_views.xml',
        'views/dg_set_procedure_views.xml',
        'views/emergency_mock_drill_views.xml',
        'views/health_checkup_views.xml',
        'views/fire_system_views.xml',
        'views/environment_plan_views.xml',
        'views/emergency_contact_views.xml',
        'views/canteen_committe_views.xml',
        'views/canteen_meeting_views.xml',
        'views/first_aid_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
