{

    'name': 'Quality Reports',
    'version': '16.0.1.0',
    'category': 'Custom',
    'summary': '',
    'description': """""",
    'author': 'ASD',
    'price': 0,
    'license': 'LGPL-3',
    'sequence': 1,
    'currency': "INR",
    'depends':['base','product','iatf','board','customer_complaint_handling','global_translation'],
    'data':[
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/inprocess.xml',
        'views/incoming.xml',
        'views/predispatch.xml',
        'views/process.xml',
        'views/risk_analysis_view.xml',
        'views/pfmea_suggestions_views.xml',
        'views/dashboard_view.xml',
        'views/dashboard.xml',
        'views/non_con_view.xml',
        'views/production_views.xml',
        'views/oee_analysis_views.xml',
        'views/ppm_analysis_views.xml',
        'views/qms_rejection_views.xml',

    ],
'css': ['static/src/css/dashboard_style.css'],
'installable': True,
    'application': True,
}
